spring:
    profiles:
        active:
        - dev
---

server: 
    port: 8001
   
spring:
    profiles: dev
    application: 
        name: microservicecloud-config-provider-dept
    datasource: 
        type: com.alibaba.druid.pool.DruidDataSource            #数据源类型
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://106.15.59.65:3306/cloudDB01?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: youyu_db_user
        password: Youyu@1881%mysql
    dbcp2: 
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200
      
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml         #mybatis配置文件所在路径
    type-aliases-package: com.ityangzi.springcloud.entities    #所有Entity别名类所在包
    mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                        #mapper映射文件   
      
eureka:
    client: #客户端注册进eureka服务列表内
    service-url: 
        defaultZone: http://eureka7001.com:7001/eureka
    instance:
        instance-id: microservicecloud-dept8001         #自定义服务名字
        prefer-ip-address: true
---
server: 
    port: 8001
   
spring:
    profiles: dev
    application: 
        name: microservicecloud-config-provider-dept
    datasource: 
        type: com.alibaba.druid.pool.DruidDataSource            #数据源类型
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://106.15.59.65:3306/cloudDB02?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: youyu_db_user
        password: Youyu@1881%mysql
    dbcp2: 
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200
      
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml         #mybatis配置文件所在路径
    type-aliases-package: com.ityangzi.springcloud.entities    #所有Entity别名类所在包
    mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                        #mapper映射文件   
      
eureka:
    client: #客户端注册进eureka服务列表内
    service-url: 
        defaultZone: http://eureka7001.com:7001/eureka
    instance:
        instance-id: microservicecloud-dept8001         #自定义服务名字
        prefer-ip-address: true
 
info:
    app.name: ityangzi-microservicecloud
    company.name: www.ityangzi.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$

    
 
 
